sonar.projectKey=cloudbatch818-aws-3-tier
sonar.projectName=cloudbatch818 AWS 3-Tier Application
sonar.sources=app/backend
sonar.tests=app/backend/tests
sonar.exclusions=app/backend/static/**,app/backend/tests/**
